### PR TITLE
feat: Add and Deleting Annotations & Componets

### PR DESCRIPTION
**Pull request by MatthewSword7272**
Feature Branch
## :scroll: Changes

- User can now add annotations based on what accordion they clicked
- Accordions can move to Annotations (for Adding) and back to Missing (for Deleting)

## :fire: Motivations

- This is one of the main features in the Application
##  :warning: Related issue

Approve the Dialog Box PR before approving this one
## Screenshots

<table>
<tr><td width=600 valign="top">
<p align=center><b>:rewind: Before</b></p>

</td>
<td width=600 valign="top">
<p align=center><b>:sparkles: After</b></p>

</td></tr>
</table>

### CODE REVIEW

**Comment by Ryan5358** [comment]
For the accordions, can you separate the action and expand behaviour by segmenting the buttons. The left segment displaying the text component should perform the actions and the right one that only shows an arrow will expand the accordion.

**Comment by MatthewSword7272** [comment]
This is kind of an impossability. I can't sperate the arrow from the header. The Accordion itself is its own deciated compoent. Trying to seperate it to make sure it does not expand when I click on it to add annotations will take alot of uneeded time and effort. I swear, I try to figure it out, but the accodtions is like a singlar button. It can't be seperated into two.

**Comment by Ryan5358** [comment]
My attempt was to utilise the header prop that supports HTML and add the handleAccordionClick to onclick event of the header segment only but the problem is it only covers the exact length of the content, not the segment.

Ok, we will figure that out later. For the meantime, please apply the following styles to the highlights or `<mark>` elements

```css
padding: 3px 5px;
border-radius: 5px;
```

**Review by Ryan5358 — APPROVED** [review]
lgtm

**Pull request merged**
