### PR TITLE
Feat: Created Dialog and other Fixes

### PR DESCRIPTION
**Pull request by MatthewSword7272**
## :scroll: Changes

- Added Dialog Box
- Accordions can now have a multiple of colours individually
- Added Axios for posting pronouns (Lohan's Request)
## Screenshots

<table>
<tr><td width=600 valign="top">
<p align=center><b>:rewind: Before</b></p>

</td>
<td width=600 valign="top">
<p align=center><b>:sparkles: After</b></p>

</td></tr>
</table>

### CODE REVIEW

**Comment by Ryan5358** [comment]
**Regarding UI**
- The dialog/popup box (box):
  - Should cover the whole annotation pane or side panel. Simply setting both dimensions to 100%. Use rounded corner for the box.
image
  - Reduce the gap between accordions to 10px.
  - Box should not be movable
- **Annotate** and **Save** buttons should not appear/be active at the same time. Only ONE active button should be shown to the user. See below for suggested solution.

**Regarding code implementations**
- Conditionally render the component depending on a processing state ('Annotate', 'Save'):
   -  `Suggested Solution` Switching from the former state to the latter state occurs once only when user clicks the **Annotate** button. The latter state should persist when a skill has been annotated by machine.
- `Suggestion` Currently the colors prop is rendered in HTML which is unwanted. It would be better if you can figure out how to not render that attribute in HTML.
image
   - `Attempt the fix`: My suggestion is to consult the [document](https://styled-components.com/docs/basics#passed-props) and examine `StyledAccordion` and `SidePanel`.

Note that you are not required to fix feature tagged with `Suggestion` but I would really appreciate your attempts.

**Comment by MatthewSword7272** [comment]
To do:
Round Corners on Dialog Box
Switch between states of Annotate and Save buttons

**Comment by Ryan5358** [comment]
Can you reduce the shadow spread? Probably the same as other panels in the side panel. Other than that, lgtm.

**Comment by Ryan5358** [comment]
LGTM

**Pull request merged**
